### ISSUE TITLE
Setup AWS access

### ISSUE THREAD

**Issue by JohnMart1218** [Mrosa99/CoffeeShop#11]
### **Scope**
---
To begin development, we will need to setup AWS access to everyone on the team. This issue focuses on granting AWS access to a single account by creating Users in IAM.

### **Value/Benefit**
---
* We will grant AWS access to developers on the team

### **Task(s)**
---
- [x] Choose an AWS account that we will all work under
- [x] Setup User access in IAM
- [x] Verify access for each User

**Comment by Mrosa99** [comment]
All users have AWS access through Milton.
