### ISSUE TITLE
EC2 Setup

### ISSUE THREAD

**Issue by Mrosa99** [Mrosa99/CoffeeShop#15]
### **Scope**
---
Creating an EC2 environment for the group will involve setting up and configuring Amazon EC2 instances to meet the specific requirements of the project, ensuring secure access and optimal performance. This includes defining the instance type, configuring networking and security settings.

### **Value/Benefit **
---
 Deploys necessary software and tools for collaborative development and testing.

### **Task(s)**
---
- [ ] Launch EC2 instance
- [ ] Set up keys
- [ ] Set up user for individual members
- [ ] Grant access to individual public keys
- [ ] Ensure access to group members
